annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/kube-version: '>= 1.32.0-0 < 1.35.0-0'
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/rancher-version: '>= 2.13.0-0 < 2.14.0-0'
  catalog.cattle.io/release-name: rancher-ali-operator-crd
apiVersion: v2
appVersion: 1.13.1
description: Ali Operator CustomResourceDefinitions
name: rancher-ali-operator-crd
version: 1.13.1
